name = "MJDSigGen"
uuid = "0b925020-e659-485c-98dd-189633cb4be4"
version = "0.2.0"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"
